 var result=document.getElementsByClassName('subheader')[0];
    var div1= document.createElement('div');
    div1.id="applimsg";
    result.appendChild(div1);
    var img1=document.createElement('img');
    img1.classList.add('imessagecont');
    img1.id="fermerboutton";
    img1.setAttribute('src',"https://cdn.iconscout.com/public/images/icon/premium/png-512/cancel-cross-delete-letter-x-remove-3c90434ffe690e93-512x512.png");
    img1.setAttribute('width',"12");
    img1.setAttribute("height","12");
    var img2 =document.createElement('img');
    img2.classList.add('imessagecont');
    img2.setAttribute("src","");
    img2.setAttribute("width","32");
    img2.setAttribute("height","32");
    var textmsg=document.createElement("p");
    textmsg.classList.add("imessagecont");
    textmsg.innerHTML="Kademia est plus rapide sur sa nouvelle application android : faites l'experience";
    var alink=document.createElement('a');
    alink.classList.add("imessagecont");
    alink.setAttribute("href","");
    alink.id='element2';
    alink.innerHTML="Cliquez ici";
    div1.appendChild(img1);
    div1.appendChild(img2);
    div1.appendChild(textmsg);
    div1.appendChild(alink);
    img1.addEventListener("click",function(event){
        div1.style.display="none";
    });
